version: "3"

services:
  db:
    image: mysql:5.7
    user: "1000:50"
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=shortLinks
      - MYSQL_USER=root
    volumes:
      - "./database/mysql:/var/lib/mysql"
      - "./database/schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    ports:
      - "3306:3306"
    container_name: mysql