FROM scratch

ENV SHORTENER_SERVER_HOST 127.0.0.1
ENV SHORTENER_SERVER_PORT 8080

ENV SHORTENER_STORAGE_HOST db
ENV SHORTENER_STORAGE_PORT 3306

EXPOSE $SHORTENER_SERVER_PORT

COPY bin/urlShotener /
COPY config/config.toml /config/

CMD ["./urlShotener"]
